export default {
    GUARITOS_CONTRACT_ADDRESS: process.env.NEXT_PUBLIC_GUARITOS_CONTRACT_ADDRESS as string,
    GUARITOS_NFT_DAO_ADDRESS: process.env.NEXT_PUBLIC_GUARITOS_NFT_DAO_ADDRESS as string,
    GUARITOS_DAO_BLACKLIST_ADDRESS: process.env.NEXT_PUBLIC_GUARITOS_DAO_BLACKLIST_ADDRESS as string,
}