import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Provider } from "./provider";
import { Center } from "@chakra-ui/react";
import { Header } from "@/components/global/bars";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable}`}
        style={{
          zIndex: -2,
        }}
      >
        <Provider>
          <Center w={"full"} h={"100vh"} display={"flex"} flexDirection="column">
            <Header />
            {children}
          </Center>
        </Provider>
      </body>
    </html>
  );
}
